import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

export const metadata = {
  title: "UAS BIG DATA - ZIYAD AYU TIAN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AppRouterCacheProvider options={{ key: 'css',  enableCssLayer: false}}>
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
